#!/usr/bin/env node
/**
 * Sui payment helper for the host.
 * Deterministically derives a wallet from the IDi (same scheme as regist-web) and does balance inquiry / transfers.
 * Invoked by the facepay daemon via subcommands; prints one line of JSON.
 *
 *   node sui-pay.mjs address <idiHex>
 *   node sui-pay.mjs balance <idiHex>
 *   node sui-pay.mjs pay     <idiHex> <amountMist> <merchantAddr>
 *   node sui-pay.mjs verify  <idiHex>            (ZK verification only; for connectivity checks)
 *
 * Payments require zero-knowledge proof verification. `pay` moveCalls
 * felica_oracle::suicash_gate::verify at the head of the same PTB, so if the
 * oracle's Groth16 proof does not verify on-chain, the whole transfer aborts.
 * There is no transfer path without a proof.
 *
 * Environment variables:
 *   SUI_RPC              fullnode JSON-RPC (defaults to publicnode testnet)
 *   SUICASH_GATE_PKG     felica_oracle package ID (takes precedence over gate.json)
 *   SUICASH_GATE_OBJ     shared Gate<SUICASH> object ID (likewise)
 *   SUICASH_ATTESTATION  attestation JSON (injected by the facepay daemon):
 *     { "idi": hex8, "attested_at": unixSec, "r1": hex8,
 *       "proof": hexCompressed, "public_inputs": hex96 }
 *
 * gate.json (same directory as this file, generated by the publish script):
 *   { "package": "0x…", "gate": "0x…" }
 *
 * ⚠ The derivation must exactly match regist-web/src/lib/wallet.ts:
 *   seed = SHA-256("suicash-aa-wallet:v1:" || idiBytes(8)) → Ed25519 private key
 */
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { SuiClient } from "@mysten/sui/client";
import { Transaction } from "@mysten/sui/transactions";
import { webcrypto } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const RPC = process.env.SUI_RPC || "https://sui-testnet-rpc.publicnode.com";
const SEED_DOMAIN = "suicash-aa-wallet:v1:";

function hexToBytes(h) {
  const s = h.trim().toLowerCase().replace(/[^0-9a-f]/g, "");
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16);
  return out;
}

async function deriveKeypair(idiHex) {
  const idiBytes = hexToBytes(idiHex);
  const domain = new TextEncoder().encode(SEED_DOMAIN);
  const input = new Uint8Array(domain.length + idiBytes.length);
  input.set(domain, 0);
  input.set(idiBytes, domain.length);
  const seed = new Uint8Array(await webcrypto.subtle.digest("SHA-256", input));
  return Ed25519Keypair.fromSecretKey(seed);
}

/** Location of the ZK gate. Env takes precedence, then the adjacent gate.json; null if neither. */
function gateConfig() {
  const pkg = process.env.SUICASH_GATE_PKG;
  const gate = process.env.SUICASH_GATE_OBJ;
  if (pkg && gate) return { package: pkg, gate };
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    const j = JSON.parse(readFileSync(join(here, "gate.json"), "utf8"));
    if (j.package && j.gate) return j;
  } catch {}
  return null;
}

/** Attestation injected by facepay; null if malformed. */
function attestation() {
  const raw = process.env.SUICASH_ATTESTATION;
  if (!raw) return null;
  try {
    const a = JSON.parse(raw);
    if (a.idi && a.r1 && a.proof && a.public_inputs && Number.isFinite(a.attested_at)) return a;
  } catch {}
  return null;
}

/** Adds the verify moveCall to tx. Must be placed at the head of the payment PTB. */
function addVerifyCall(tx, cfg, att) {
  tx.moveCall({
    target: `${cfg.package}::suicash_gate::verify`,
    arguments: [
      tx.object(cfg.gate),
      tx.pure.vector("u8", Array.from(hexToBytes(att.idi))),
      tx.pure.u64(BigInt(att.attested_at)),
      tx.pure.vector("u8", Array.from(hexToBytes(att.proof))),
      tx.pure.vector("u8", Array.from(hexToBytes(att.public_inputs))),
      tx.pure.vector("u8", Array.from(hexToBytes(att.r1))),
      tx.object.clock(),
    ],
  });
}

/** Maps a Move abort to a user-facing message (best effort). */
function abortMessage(raw) {
  const s = String(raw || "");
  if (!/MoveAbort/.test(s)) return null;
  const mod = (s.match(/Identifier\("(\w+)"\)/) || [])[1] || "";
  const code = Number((s.match(/,\s*(\d+)\)/) || [])[1] ?? NaN);
  if (mod === "gate" && code === 1) {
    // gate::EReplay: the same r1 can only be used once
    return "This authentication has already been used. Please tap your card again";
  }
  if (mod === "gate" && code === 0) return "This card is not allowed";
  if (mod === "felica_auth" && code === 4) return "Authentication has expired. Please tap your card again";
  if (mod === "felica_auth") return "Invalid authentication data";
  if (mod === "zk_verifier") return "ZK proof verification failed";
  return "Rejected by ZK verification";
}

const client = new SuiClient({ url: RPC });

async function getBalanceMist(address) {
  const b = await client.getBalance({ owner: address });
  return BigInt(b.totalBalance);
}

function out(obj) {
  process.stdout.write(JSON.stringify(obj) + "\n");
}

async function main() {
  const [cmd, idi, a3, a4] = process.argv.slice(2);
  if (!cmd || !idi) {
    out({ ok: false, error: "usage: <address|balance|verify|pay> <idiHex> [amountMist] [merchant]" });
    process.exit(2);
  }
  const kp = await deriveKeypair(idi);
  const address = kp.getPublicKey().toSuiAddress();

  if (cmd === "address") {
    out({ ok: true, address });
    return;
  }
  if (cmd === "balance") {
    out({ ok: true, address, balance: (await getBalanceMist(address)).toString() });
    return;
  }

  if (cmd === "verify" || cmd === "pay") {
    // ZK verification is mandatory. Reject before transferring if the gate is unconfigured or the attestation is missing.
    const cfg = gateConfig();
    const att = attestation();
    if (!cfg) {
      out({ ok: false, error: "ZK gate not configured (SUICASH_GATE_PKG/SUICASH_GATE_OBJ or gate.json)", address });
      process.exit(2);
    }
    if (!att) {
      out({ ok: false, error: "No attestation (SUICASH_ATTESTATION). Payments without a proof are invalid", address });
      process.exit(2);
    }

    const tx = new Transaction();
    addVerifyCall(tx, cfg, att);

    let amount = 0n;
    let before = 0n;
    if (cmd === "pay") {
      amount = BigInt(a3);
      const merchant = a4;
      if (!merchant) {
        out({ ok: false, error: "merchant address required" });
        process.exit(2);
      }
      before = await getBalanceMist(address);
      const [coin] = tx.splitCoins(tx.gas, [amount]);
      tx.transferObjects([coin], merchant);
    }

    let res;
    try {
      res = await client.signAndExecuteTransaction({
        signer: kp,
        transaction: tx,
        options: { showEffects: true, showEvents: true },
      });
    } catch (e) {
      const msg = abortMessage(e?.message) || e?.message || String(e);
      out({ ok: false, error: msg, address });
      process.exit(1);
    }
    const status = res.effects?.status?.status;
    if (status !== "success") {
      const raw = res.effects?.status?.error || status || "tx failed";
      out({ ok: false, error: abortMessage(raw) || raw, address });
      process.exit(1);
    }
    const verifiedEvent = (res.events || []).find((ev) =>
      ev.type.endsWith("::suicash_gate::AttestationVerified")
    );

    if (cmd === "verify") {
      out({ ok: true, address, digest: res.digest, verified: Boolean(verifiedEvent) });
      return;
    }

    await new Promise((r) => setTimeout(r, 1500));
    let after;
    try {
      after = (await getBalanceMist(address)).toString();
    } catch {
      after = (before - amount).toString();
    }
    out({
      ok: true,
      address,
      amount: amount.toString(),
      balanceAfter: after,
      digest: res.digest,
      zkVerified: Boolean(verifiedEvent),
    });
    return;
  }
  out({ ok: false, error: `unknown command: ${cmd}` });
  process.exit(2);
}

main().catch((e) => {
  out({ ok: false, error: e?.message || String(e) });
  process.exit(1);
});
