apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: felica-oracle

resources:
  - namespace.yaml
  - backend.yaml
  - oracle-secret.yaml
  - oracle-config.yaml
  - ingress.yaml

images:
  - name: ghcr.io/yuki-js/suicash/oracle
    newTag: latest

labels:
  - pairs:
      app: felica-oracle
