// @generated by `felica-fixture` (prover/src/bin/felica-fixture.rs) — do not hand-edit.
//
// Ceremony output. Regenerate after any circuit, proving-key or
// verifying-key change:
//
// ```text
// cargo run --release --bin felica-fixture -- \
//     assets/proving_key.bin ../sui/felica_oracle/tests/fixture.move
// ```
module felica_oracle::fixture;

/// Arkworks canonical compressed Groth16 verifying key (BN254).
public fun vk(): vector<u8> { x"a210203d72694f05e04e1669b39df0a2716f90bb3399bab9ce7f0591f607791c6b41f1bf742025c790fd33dfd27cec5cf0f5406d5e4ee8f276b658930d15ad1ce57b7596431a52c60b71457a84cdd468ace6a97fc65a6acc857644130391fc2a6c43da7ff05171006f0b74b01c47216f6a9dd1a5ded1bb1b771ddb3bc6aff82c4a123d66e105171f125c3084d23936b6696f529d2d32e7fc9c762a11382a2e12308c4be89b04584cf918000bc6a3bd6e3a429aac0a463f35dcadf77d7d14842e255f61e157d585db07f54e10d377c23d7cffdb846e606662de66f5ce37e8dd10040000000000000059425785e2ec10006d7764de5f6b55efa01feafabf6fd1c991d8d943e000fea890d88859558a2643ec40775dd5fbed11fa3f26434b8ceebd6e85c2f327478987f0299e9f4d810b59f0d80fc1542f8628f99d83d0d3361065b6878cbd57016d1d6c27ec6802cdf38b1f5707e1f10f83ff54862381b819ecfa9d74b959a6e4d595" }

/// Arkworks canonical compressed proof points (A, B, C).
public fun proof(): vector<u8> { x"b022865da0b83aa0a5d6c9a8c0d4b1da5437564da2e41d86492fa2ed49d8c918a93e3c8a5d61802efa7914725233e4176ec14e808a3d70d1eb5ef46072bf69247c543a620b2bdce0bab7e23bd3b19910c9deef90190219402aba31bd2a96bca328dd055e42ce405d52c89fd857daf73a262c8947a48d2390a2ec0bfd17348f04" }

/// The 3 public inputs, 32B little-endian each: idi ‖ r1 ‖ attested_at.
public fun public_inputs(): vector<u8> { x"1020304050607080000000000000000000000000000000000000000000000000001122334455667700000000000000000000000000000000000000000000000080abd46800000000000000000000000000000000000000000000000000000000" }

/// Envelope IDi the proof commits to (`pi0`).
public fun idi(): vector<u8> { x"1020304050607080" }

/// Envelope timestamp the proof commits to (`pi2`), Unix seconds.
public fun attested_at(): u64 { 1758768000u64 }
