/// Tests for the on-chain verifier, against a real proof over the real
/// ceremony key (`fixture.move`, generated by `prover`'s `felica-fixture`).
///
/// Every test either verifies a genuine attestation or asserts that a specific
/// class of forgery is *rejected*. The negatives are the point: a verifier
/// whose positive case passes for the wrong reason — a stub, a mismatched key,
/// a check that quietly returns `true` — is caught by mutating one thing and
/// expecting an abort.
#[test_only]
module felica_oracle::zk_verifier_tests;

use felica_oracle::felica_auth;
use felica_oracle::fixture;
use felica_oracle::gate;
use felica_oracle::zk_verifier;
use sui::tx_context;
use std::unit_test;

const FIXED_NOW: u64 = 1_758_768_000;
const NO_DRIFT: u64 = 0;
const ONE_DAY: u64 = 86_400;
const A_YEAR: u64 = 31_536_000;

/// Empty type parameter for the gate's phantom key.
public struct Witness has drop {}

/// A genuine attestation over the fixture card.
fun genuine(): felica_auth::Attestation {
    felica_auth::new(
        b"groth16-bn254",
        fixture::idi(),
        fixture::attested_at(),
        fixture::proof(),
        fixture::public_inputs(),
    )
}

/// The `r1` the fixture proof commits to (`pi1`).
fun fixture_r1(): vector<u8> { felica_auth::r1(&genuine()) }

/// A gate admitting any card, with room for the fixture's own second.
fun open_gate(drift: u64): gate::Gate<Witness> {
    gate::create<Witness>(fixture::vk(), vector[], drift, &mut tx_context::dummy())
}

/// A gate admitting only the fixture card.
fun allowlisted_gate(drift: u64): gate::Gate<Witness> {
    gate::create<Witness>(
        fixture::vk(),
        vector[fixture::idi()],
        drift,
        &mut tx_context::dummy(),
    )
}

/// The fixture attestation with a different card claimed in the envelope. The
/// proof is untouched, so only the envelope check can reject this.
fun lying_envelope(): felica_auth::Attestation {
    felica_auth::new(
        b"groth16-bn254",
        x"ffffffffffffffff",
        fixture::attested_at(),
        fixture::proof(),
        fixture::public_inputs(),
    )
}

#[test]
fun genuine_attestation_verifies() {
    let k = zk_verifier::key(fixture::vk());
    assert!(zk_verifier::verify(&k, &genuine()) == fixture::idi());
}

/// The pinned key is what is stored, byte for byte. If this drifts, the
/// on-chain key and the Rust-side fixture describe different circuits.
#[test]
fun pinned_key_is_the_fixture_key() {
    let k = zk_verifier::key(fixture::vk());
    assert!(zk_verifier::vk_bytes(&k) == fixture::vk());
}

/// The key is pinned, not negotiated: mutating a byte of it must not leave a
/// key that still verifies this proof.
#[test]
#[expected_failure]
fun mutated_key_does_not_verify() {
    let mut vk = fixture::vk();
    *vk.borrow_mut(0) = *vk.borrow(0) ^ 0x01;
    let k = zk_verifier::key(vk);
    let _ = zk_verifier::verify(&k, &genuine());
}

#[test]
#[expected_failure(abort_code = 2)] // felica_auth::EEnvelopeInconsistent
fun forged_idi_is_rejected() {
    let k = zk_verifier::key(fixture::vk());
    // The honest attestation still verifies, so the abort below is
    // attributable to the forgery and not to a broken key or fixture.
    zk_verifier::verify(&k, &genuine());
    let _ = zk_verifier::verify(&k, &lying_envelope());
}

/// The public inputs are bound by the pairing equation, so altering one must
/// break verification even when no envelope field disagrees.
///
/// `pi1` (the holder challenge) is the interesting target: it is the only
/// scalar no envelope field mirrors, so this cannot be caught by the envelope
/// check and genuinely exercises the pairing. A forger holding the proving key
/// produces exactly this shape of forgery.
#[test]
#[expected_failure(abort_code = 1)] // zk_verifier::EProofInvalid
fun altered_challenge_scalar_is_rejected() {
    let k = zk_verifier::key(fixture::vk());
    let mut pis = fixture::public_inputs();
    *pis.borrow_mut(32) = *pis.borrow(32) ^ 0x01;
    let forged = felica_auth::new(
        b"groth16-bn254",
        fixture::idi(),
        fixture::attested_at(),
        fixture::proof(),
        pis,
    );
    // The envelope check passes: `idi` and `attested_at` are untouched. Only
    // the pairing can catch this.
    felica_auth::assert_envelope_consistent(&forged);
    let _ = zk_verifier::verify(&k, &forged);
}

/// Altering `pi0` is caught one step earlier, by the envelope check, because
/// the envelope's `idi` is exactly `pi0`. Both rejections are required; this
/// pins which one fires.
#[test]
#[expected_failure(abort_code = 2)] // felica_auth::EEnvelopeInconsistent
fun altered_idi_scalar_is_rejected() {
    let k = zk_verifier::key(fixture::vk());
    let mut pis = fixture::public_inputs();
    *pis.borrow_mut(0) = *pis.borrow(0) ^ 0x01;
    let forged = felica_auth::new(
        b"groth16-bn254",
        fixture::idi(),
        fixture::attested_at(),
        fixture::proof(),
        pis,
    );
    let _ = zk_verifier::verify(&k, &forged);
}

#[test]
#[expected_failure(abort_code = 2)] // felica_auth::EEnvelopeInconsistent
fun envelope_idi_must_match_pi0() {
    // A valid proof whose *envelope* lies about the IDi. The pairing equation
    // is untouched, so only the envelope check can catch it — which is exactly
    // the gap `assert_envelope_consistent` exists to close.
    let k = zk_verifier::key(fixture::vk());
    let _ = zk_verifier::verify(&k, &lying_envelope());
}

#[test]
#[expected_failure(abort_code = 2)] // felica_auth::EEnvelopeInconsistent
fun envelope_timestamp_must_match_pi2() {
    let k = zk_verifier::key(fixture::vk());
    let att = felica_auth::new(
        b"groth16-bn254",
        fixture::idi(),
        fixture::attested_at() + 1,
        fixture::proof(),
        fixture::public_inputs(),
    );
    let _ = zk_verifier::verify(&k, &att);
}

#[test]
#[expected_failure(abort_code = 1)] // felica_auth::EUnsupportedAlg
fun unknown_alg_is_rejected() {
    let _ = felica_auth::new(
        b"groth16-bls12381",
        fixture::idi(),
        fixture::attested_at(),
        fixture::proof(),
        fixture::public_inputs(),
    );
}

#[test]
#[expected_failure(abort_code = 0)] // felica_auth::EMalformed
fun wrong_public_input_length_is_rejected() {
    // `take` because this stdlib has no `pop`.
    let pis = std::vector::take(fixture::public_inputs(), 95);
    let _ = felica_auth::new(
        b"groth16-bn254",
        fixture::idi(),
        fixture::attested_at(),
        fixture::proof(),
        pis,
    );
}

#[test]
#[expected_failure(abort_code = 2)] // felica_auth::EEnvelopeInconsistent
fun non_canonical_scalar_is_rejected() {
    // A `pi0` with a non-zero byte above the 8-byte limb. The value denotes
    // the same field element, so the pairing could still hold — only the
    // canonicality rule rejects it, and without that rule two distinct blobs
    // would describe one statement.
    let mut pis = fixture::public_inputs();
    *pis.borrow_mut(8) = 0x01;
    let att = felica_auth::new(
        b"groth16-bn254",
        fixture::idi(),
        fixture::attested_at(),
        fixture::proof(),
        pis,
    );
    // Construction only checks shape; the canonicality rule is enforced where
    // the statement is read.
    felica_auth::assert_envelope_consistent(&att);
}

#[test]
#[expected_failure(abort_code = 0)] // felica_auth::EMalformed
fun idi_of_wrong_length_is_rejected() {
    let _ = felica_auth::new(
        b"groth16-bn254",
        x"0102030405",
        fixture::attested_at(),
        fixture::proof(),
        fixture::public_inputs(),
    );
}

#[test]
fun gate_accepts_and_returns_idi() {
    let mut g = open_gate(ONE_DAY);
    let idi = gate::verify_and_claim(&mut g, &genuine(), fixture_r1(), FIXED_NOW);
    assert!(idi == fixture::idi());
    assert!(gate::is_seen(&g, fixture_r1()));
    unit_test::destroy(g);
}

#[test]
#[expected_failure(abort_code = 1)] // gate::EReplay
fun gate_burns_r1() {
    let mut g = open_gate(ONE_DAY);
    let att = genuine();
    let r1 = fixture_r1();
    gate::verify_and_claim(&mut g, &att, r1, FIXED_NOW);
    // Same attestation, same challenge, second time: a replay. Without the
    // dedup store this would succeed and the attestation would be spendable
    // twice.
    gate::verify_and_claim(&mut g, &att, r1, FIXED_NOW);
    unit_test::destroy(g);
}

/// A rejected presentation aborts, and the abort happens *before* the burn —
/// the ordering in `gate::verify_and_claim` is what stops an attacker from
/// invalidating a legitimate holder's pending challenge by submitting a bad
/// presentation first.
///
/// Move has no exception handling, so "aborts, and the state is untouched" is
/// the strongest form available: the whole transaction, state changes
/// included, is reverted. The ordering is load-bearing in a way a passing test
/// cannot demonstrate by itself; this pins only that a rejection is an abort
/// rather than a `false` return.
#[test]
#[expected_failure(abort_code = 2)] // felica_auth::EEnvelopeInconsistent
fun rejected_claim_aborts() {
    // Open allowlist: the allowlist is checked *before* the proof, so a
    // restricted gate would abort with `ENotAllowed` and never reach the
    // rejection under test.
    let mut g = open_gate(ONE_DAY);
    gate::verify_and_claim(&mut g, &lying_envelope(), fixture_r1(), FIXED_NOW);
    unit_test::destroy(g);
}

#[test]
#[expected_failure(abort_code = 3)] // felica_auth::EChallengeMismatch
fun gate_rejects_a_foreign_challenge() {
    // A verifier that never issued this challenge must not accept the
    // presentation, even though the proof is genuine and the IDi allowed.
    let mut g = allowlisted_gate(ONE_DAY);
    gate::verify_and_claim(&mut g, &genuine(), x"aabbccddeeff0011", FIXED_NOW);
    unit_test::destroy(g);
}

#[test]
#[expected_failure(abort_code = 0)] // gate::ENotAllowed
fun gate_enforces_the_allowlist() {
    let mut g = gate::create<Witness>(
        fixture::vk(),
        vector[x"0000000000000000"],
        ONE_DAY,
        &mut tx_context::dummy(),
    );
    gate::verify_and_claim(&mut g, &genuine(), fixture_r1(), FIXED_NOW);
    unit_test::destroy(g);
}

#[test]
#[expected_failure(abort_code = 4)] // felica_auth::EClockDrift
fun gate_rejects_absurd_drift() {
    // A year of drift: the coarse signal is meant to catch exactly this.
    let mut g = open_gate(ONE_DAY);
    gate::verify_and_claim(&mut g, &genuine(), fixture_r1(), FIXED_NOW + A_YEAR);
    unit_test::destroy(g);
}

/// With `max_clock_drift_seconds = 0` the check is exact, so the fixture's own
/// timestamp is accepted. Pins that the drift check reads `attested_at` rather
/// than passing vacuously.
#[test]
fun exact_drift_accepts_the_claimed_second() {
    let mut g = open_gate(NO_DRIFT);
    assert!(gate::verify_and_claim(&mut g, &genuine(), fixture_r1(), FIXED_NOW) == fixture::idi());
    assert!(gate::is_seen(&g, fixture_r1()));
    unit_test::destroy(g);
}

#[test]
#[expected_failure(abort_code = 4)] // felica_auth::EClockDrift
fun exact_drift_rejects_one_second_late() {
    let mut g = open_gate(NO_DRIFT);
    gate::verify_and_claim(&mut g, &genuine(), fixture_r1(), FIXED_NOW + 1);
    unit_test::destroy(g);
}

#[test]
#[expected_failure(abort_code = 4)] // felica_auth::EClockDrift
fun exact_drift_rejects_one_second_early() {
    let mut g = open_gate(NO_DRIFT);
    gate::verify_and_claim(&mut g, &genuine(), fixture_r1(), FIXED_NOW - 1);
    unit_test::destroy(g);
}

#[test]
fun an_empty_allowlist_means_open() {
    let mut g = open_gate(ONE_DAY);
    assert!(gate::is_open(&g));
    assert!(gate::is_idi_allowed(&g, x"0102"));
    unit_test::destroy(g);
}

/// The reason `allow_any` is a flag and not "list is empty": touching the
/// allowlist must never be able to widen the gate. Removing the last entry
/// leaves a closed gate that admits nothing, not an open one.
#[test]
fun narrowing_is_irreversible() {
    let mut g = allowlisted_gate(ONE_DAY);
    assert!(!gate::is_open(&g));
    assert!(gate::is_idi_allowed(&g, fixture::idi()));
    assert!(!gate::is_idi_allowed(&g, x"0102"));
    gate::disallow(&mut g, fixture::idi());
    assert!(!gate::is_open(&g));
    assert!(!gate::is_idi_allowed(&g, fixture::idi()));
    gate::allow(&mut g, fixture::idi());
    assert!(!gate::is_open(&g));
    assert!(gate::is_idi_allowed(&g, fixture::idi()));
    unit_test::destroy(g);
}

#[test]
fun allow_and_disallow() {
    let mut g = open_gate(ONE_DAY);
    gate::allow(&mut g, x"0102");
    assert!(gate::is_idi_allowed(&g, x"0102"));
    assert!(!gate::is_idi_allowed(&g, x"0304"));
    gate::disallow(&mut g, x"0102");
    assert!(!gate::is_idi_allowed(&g, x"0102"));
    unit_test::destroy(g);
}

#[test]
#[expected_failure(abort_code = 2)] // gate::EUnknownIdi
fun disallow_of_an_absent_idi_aborts() {
    let mut g = open_gate(ONE_DAY);
    gate::disallow(&mut g, x"0102");
    unit_test::destroy(g);
}
